nginx:
  container_name: nginx.boilerplate
  image: nginx
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./www/:/var/www/nginx.boilerplate/:ro
    - ./src/:/etc/nginx/:ro
    - ./test/logs:/var/log/nginx/
  links:
    - php

php:
  container_name: php.nginx.boilerplate
  image: php:fpm
  expose:
    - 9000
  volumes:
    - ./www-fpm/:/var/www/nginx.boilerplate/:ro
